# Default values for the Istio wrapper chart.
# Provider-specific overrides go in values/providers/<provider>/istio.yaml

base:
  defaultRevision: default

istiod:
  pilot:
    autoscaleEnabled: false
    replicaCount: 1

    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true

  meshConfig:
    accessLogFile: /dev/stdout
