apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchLabels:
            provider: proxmox
  template:
    metadata:
      name: 'metallb-{{.name}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/lowranceworks/k8s-platform.git
          targetRevision: main
          path: charts/metallb
          helm:
            valueFiles:
              - $values/values/providers/proxmox/metallb.yaml
        - repoURL: https://github.com/lowranceworks/k8s-platform.git
          targetRevision: main
          ref: values
      destination:
        server: '{{.server}}'
        namespace: metallb-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
