apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: personal
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Personal project - manages core infrastructure and cluster services

  sourceRepos:
    - 'https://github.com/lowranceworks/k8s-platform.git'
    - '*'

  destinations:
    - namespace: '*'
      server: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: true
