apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-projects
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lowranceworks/k8s-platform.git
    targetRevision: HEAD
    path: argocd/app-projects
    directory:
      recurse: true
      include: '*.yaml'
      exclude: 'README.md'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application-sets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lowranceworks/k8s-platform.git
    targetRevision: HEAD
    path: argocd/application-sets
    directory:
      recurse: true
      include: '*.yaml'
      exclude: 'README.md'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lowranceworks/k8s-platform.git
    targetRevision: HEAD
    path: argocd/applications
    directory:
      recurse: true
      include: '*.yaml'
      exclude: 'README.md'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-clusters
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lowranceworks/k8s-platform.git
    targetRevision: HEAD
    path: argocd/clusters
    directory:
      recurse: true
      include: '*.yaml'
      exclude: 'README.md'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
