{{- if .Values.cloudflare.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-personal-secrets
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.cloudflare.gcpProjectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
            namespace: external-secrets
{{- end }}
