{{- if .Values.cloudflare.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-api-token
spec:
  refreshInterval: {{ .Values.cloudflare.refreshInterval | default "1h" }}
  secretStoreRef:
    name: gcp-personal-secrets
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cloudflare.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: {{ .Values.cloudflare.remoteKey }}
{{- end }}
