apiVersion: v1
kind: Secret
metadata:
  name: dev-proxmox-home
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    lifecycle: dev
    provider: proxmox
    region: home
type: Opaque
stringData:
  name: dev-proxmox-home
  server: https://192.168.1.220:6443
  # config is populated by ExternalSecret
